title: "SIC DA posteriors"
description: "posterior sea ice concentration (SIC) states after data assimilation (DA) (https://doi.org/10.1175/JCLI-D-20-0469.1)"
pangeo_forge_version: "0.8.3"
recipes:
  - id: sic-post
    object: "recipe:recipe"
provenance:
  providers:
    - name: "NOAA GFDL"
      description: "National Oceanic and Atmospheric Administration (NOAA) Geophysical Fluid Dynamics Laboratory (GFDL)"
      roles:
        - producer
        - licensor
      url: https://doi.org/10.1175/JCLI-D-20-0469.1
  license: "proprietary"
maintainers:
  - name: "William Gregory"
    orcid: "0000-0001-8176-1642"
    github: William-gregory
bakery:
  id: "pangeo-ldeo-nsf-earthcube"
