title: "GFDL SIC DA"
description: "model ensemble mean state vectors and diagnostics, and input observations from SPEAR sea ice concentration (SIC) data assimilation (DA) run"
pangeo_forge_version: "0.8.3"
recipes:
  - id: sic-da
    object: "recipe:recipe"
provenance:
  providers:
    - name: "NOAA GFDL"
      description: "National Oceanic and Atmospheric Administration (NOAA) Geophysical Fluid Dynamics Laboratory (GFDL)"
      roles:
        - producer
        - licensor
      url: https://doi.org/10.1175/JCLI-D-20-0469.1 (model) / https://nsidc.org/data/NSIDC-0051/versions/1 (obs)
  license: "various"
maintainers:
  - name: "William Gregory"
    orcid: "0000-0001-8176-1642"
    github: William-gregory
bakery:
  id: "pangeo-ldeo-nsf-earthcube"
