name: Create Repository

on:
  push:
    branches: "master"

jobs:
  test:
    name: Check Recipes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
      - name: Check for new recipes
        env:
          GH_API_TOKEN: ${{ secrets.GH_API_TOKEN }}
        run: |
          python -m pip install requests
          git config --global user.name 'pangeo-bot'
          git config --global user.email 'pangeo-bot@users.noreply.github.com'
          python .github/workflows/scripts/add_new_recipes.py
