name: Create Repository

on:
  push:
    branches: "master"

jobs:
  test:
    name: Check Recipes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
      - name: Check for new recipes
        run: |
          python -m pip install requests
          python .github/workflows/scripts/add_new_recipes.py
