name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: master

jobs:
  test:
    name: Check Recipes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install pangeo-forge
        shell: bash -l {0}
        run: |
          python -m pip install git+https://github.com/pangeo-forge/pangeo-forge
      - name: Lint recipes
        shell: bash -l {0}
        run: |
          for dir in recipes/*; do
            pangeo-forge check ${dir} --verbose
          done;
