name: Process PR Recipe

on:
  push:
    branches: ["*"]
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  process-recipe:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - id: changed-files
        name: Get the files changed in the Pull Request
        uses: jitterbit/get-changed-files@v1

      - name: Locate Pull Requests recipe.py
        id: recipe
        run: |
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            if [[ ${changed_file} =~ ^.*recipes\/.*recipe\.py$ ]];
            then
              echo "::set-output name=RECIPE_PY::${changed_file}";
              exit 0
            fi
          done
          exit 1 # Fail - recipe.py required

      - name: Locate Pull Requests meta.yaml
        id: meta
        run: |
          for changed_file in ${{ steps.changed-files.outputs.all }}; do
            if [[ ${changed_file} =~ ^.*recipes\/.*meta\.(yml|yaml)$ ]];
            then
              echo "::set-output name=META_YAML::${changed_file}";
              exit 0
            fi
          done
          exit 1 # Fail - meta.yaml required

      - name: Process Pull Requests recipe
        if: ${{ steps.recipe.outputs.RECIPE_PY != null && steps.meta.outputs.META_YAML != null }}
        uses: ./.github/actions/process_recipe
        with:
          path_to_recipe_py: ${{ steps.recipe.outputs.RECIPE_PY }}
          path_to_meta_yaml: ${{ steps.meta.outputs.META_YAML }}
